version: '3.5'

services:
  db:
    container_name: nest_todo_db
    image: postgres
    restart: 'no'
    env_file:
      - .env
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
